# Generated by Django 4.1.3 on 2022-11-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Kit name')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Home'), (1, 'Car'), (2, 'Office')], verbose_name='Type')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='users.user', verbose_name='Owner')),
            ],
        ),
    ]
