# Generated by Django 4.1.3 on 2022-11-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('expire_date', models.DateTimeField(verbose_name='Expire date')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Salve'), (1, 'Drop'), (2, 'Capsule'), (3, 'Pill')], verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Char Field')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='kits.kit', verbose_name='Kit')),
            ],
        ),
    ]
